- name: Install loader tools
  hosts: loader
  tasks:
  - name: Ensure necessary packages are installed
    apt:
      name: [git, maven]
      state: present
    become: yes

  - name: Download YCSB - Remove old YCSB directory if exists
    file:
      path: /home/ubuntu/YCSB
      state: absent
    #become: yes

  - name: Clone the YCSB repository
    git:
      repo: https://github.com/brianfrankcooper/YCSB.git
      dest: /home/ubuntu/YCSB
      force: yes
    #become: yes

  - name: Build YCSB with Scylla and DynamoDB bindings
    command: mvn -pl site.ycsb:scylla-binding,site.ycsb:dynamodb-binding -am clean package -DskipTests
    args:
      chdir: /home/ubuntu/YCSB
    #become: yes