---
- name: Restart Scylla Server on NonSeed Nodes
  hosts: scylla_nonseed
  become: yes  # This playbook needs to run with sudo to manage system services
  tasks:
    - name: Stop the Scylla service
      ansible.builtin.systemd:
        name: scylla-server
        state: stopped

    - name: Start Scylla server and wait for it to be 'serving'
      ansible.builtin.shell: |
        sudo systemctl start scylla-server
        sleep 10  # Initial delay to let Scylla start up
        until systemctl status scylla-server | grep -q "Status: \"serving\""; do sleep 10; done
      async: 400  # Set an overall timeout for the operation (e.g., 700 seconds)
      poll: 10    # Check every 10 seconds
      throttle: 1
      changed_when: false

    - name: Check if Scylla service is active
      ansible.builtin.command: systemctl is-active scylla-server
      register: scylla_service_active
      failed_when: false
      # We do not want this task to fail the playbook; instead, we will use its result to decide if we need to restart.

    - name: Restart Scylla server if it is not active
      ansible.builtin.systemd:
        name: scylla-server
        state: restarted
      when: scylla_service_active.stdout != "active"
      # This task restarts the Scylla server if the previous check finds the service is not active.
