---
plugin: aws_ec2

regions:
 - us-east-1

filters:
 instance-state-name: 'running'
 tag:Project:
   - 'Ricardo-Benchmark'

groups:
  scylla:   (tags['Type'] is defined and tags['Type'] == 'Scylla')
  aws_loader: (tags['Type'] is defined and tags['Type'] == 'Loader')
  aws_monitor: (tags['Type'] is defined and tags['Type'] == 'Monitoring')

keyed_groups:
  # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags
